# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3-video.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3-video.yml down`
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.1.2-20220208
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5

  firefox:
    image: selenium/node-firefox:4.1.2-20220208
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  chrome_video:
    image: selenium/video:ffmpeg-4.3.1-20220208
    volumes:
      - D:\\grid4:/videos
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=chrome_video.mp4

  firefox_video:
    image: selenium/video:ffmpeg-4.3.1-20220208
    volumes:
      - D:\\grid4:/videos
    depends_on:
      - firefox
    environment:
      - DISPLAY_CONTAINER_NAME=firefox
      - FILE_NAME=firefox_video.mp4
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5

  selenium-hub:
    image: selenium/hub:4.1.2-20220208
    container_name: selenium-hub
    environment:
    - GRID_MAX_SESSION=5
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  google-module:
    image: boot_openjdk11_new13/spring-tests
    depends_on:
      - chrome
      - firefox
    environment:
      - browser=firefox
      - module=testng-suite.xml
    volumes:
      - D:\\grid4\\google-result2:/usr/share/udemy/test-output
